# Generated by Django 3.2.8 on 2021-10-09 16:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0002_auto_20211009_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=10, verbose_name='Nit')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre de la Empresa')),
                ('nombre_comercial', models.CharField(max_length=250, verbose_name='Nombre Comercial')),
                ('direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Por favor escribe el numero en el formato aceptado sin código de área ej: 3123456789', regex='^(3)([0-9]){11}$')], verbose_name='Telefono')),
                ('email', models.EmailField(max_length=250, verbose_name='Correo electronico')),
                ('web', models.CharField(max_length=250, verbose_name='Sito Web')),
                ('paisestadociudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.paisestadociudad', verbose_name='Pais, Estado, Ciudad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario de la empresa')),
                ('usuarios', models.ManyToManyField(related_name='usuarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios de la empresa')),
            ],
        ),
    ]
