# Generated by Django 3.2.8 on 2021-10-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_invitaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitaciones',
            name='estado',
            field=models.CharField(choices=[('Espera', 'Espera'), ('Rechazada', 'Rechazada'), ('Aceptada', 'Aceptada')], default='Espera', max_length=10),
        ),
    ]
