# Generated by Django 3.2.8 on 2021-10-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_alter_invitaciones_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitaciones',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa'),
        ),
    ]
