# Generated by Django 3.2.8 on 2021-10-11 01:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_alter_invitaciones_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContanctosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=250, verbose_name='Correo electronico')),
                ('telefono', models.CharField(max_length=150, unique=True, verbose_name='Telefono Fijo')),
                ('celular', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='invitaciones',
            name='estado',
            field=models.CharField(choices=[('Espera', 'Espera'), ('Aceptada', 'Aceptada')], default='Espera', max_length=10),
        ),
        migrations.CreateModel(
            name='EmpresaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=13, verbose_name='Nit')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre de la Empresa')),
                ('nombre_comercial', models.CharField(max_length=250, verbose_name='Nombre Comercial')),
                ('direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=250, verbose_name='Correo electronico')),
                ('web', models.CharField(max_length=250, unique=True, verbose_name='Sito Web')),
                ('contacto', models.ManyToManyField(to='empresa.ContanctosEmpresa', verbose_name='Contactos de la empresa')),
                ('paisestadociudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.paisestadociudad', verbose_name='Pais, Estado, Ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='contanctosempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresacliente', verbose_name='Empresa de la que son contacto '),
        ),
    ]
