# Generated by Django 3.2.8 on 2021-10-11 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0012_auto_20211010_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contanctosempresa',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresacliente', verbose_name='Empresa de la que son contacto '),
        ),
    ]
